# Generated by Django 5.0.3 on 2024-04-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoryQnA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryQnAExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(blank=True)),
                ('categoryQnA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryQnA.categoryqna')),
            ],
        ),
    ]
