# Generated by Django 5.0.3 on 2024-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoryQnAExamples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryqnaexamples',
            name='reference_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
