# Generated by Django 5.0.3 on 2024-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verify_email',
            field=models.BooleanField(default=False),
        ),
    ]
